### ISSUE TITLE
isArt判断逻辑需要改进

### ISSUE THREAD

**Issue by cddjr** [boyliang/AllHookInOne#5]
现有的方式是去判断persist.sys.dalvik.vm.lib， 但是5.0似乎不是这个key了，改为persist.sys.dalvik.vm.lib.2 
这会让现有的逻辑在5.0上误判为dvm?

另外这里给一个通用判断：
读取/proc/self/maps，如果当前进程是ART,则能找到/system/lib/libart.so, 反之则能找到/system/lib/libdvm.so, 都找不到那就不是java进程。
64位进程则是/system/lib64/xxxx

**Comment by wenq1** [comment]
/proc/self/maps 国内很多非root机型读不到

**Comment by cddjr** [comment]
@wenq1  拜托，别以为看到一个/proc开头就说要root权限，这个是/proc/self/ 你懂啥叫self不？  这个不需要root，不管什么国内外、5.0、6.0系统。。。。。。  建议你还是先把linux搞明白再来研究Android

**Comment by KingPaul** [comment]
@wenq1 cddjr说的对，/proc/self不需要root，因为是自己的进程空间嘛，肯定自己是可以访问的.
另外，引用developer上的一句话，
You can verify which runtime is in use by calling System.getProperty("java.vm.version"). If ART is in use, the property's value is "2.0.0" or higher.
我们可以这样判断是否是art环境。
